version: 2
registries:
  nuget-org:
    type: nuget-feed
    url: https://api.nuget.org/v3/index.json
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    registries:    
      - nuget-org
    schedule:
      interval: "daily"    
    open-pull-requests-limit: 5
    reviewers: 
      - "ingridTPires"
    commit-message:
      prefix: "chore"
      include: "scope"
    target-branch: "main"
    allow:
      - dependency-name: "Z.EntityFramework.Extensions"
